services:
  - type: web
    name: twoae-demo-web
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: PORT
        value: "10000"
      - key: NEXT_PUBLIC_APP_NAME
        value: 2AE VENTURES
      - key: NEXT_PUBLIC_DEFAULT_LOCALE
        value: vi
      - key: NEXT_PUBLIC_ENABLED_LOCALES
        value: vi,en
